### ISSUE TITLE
导入不了这个注册的组件

### ISSUE THREAD

**Issue by YuFy1314** [OwnGhy/vue-fun-loading#12]
![image](https://user-images.githubusercontent.com/24446694/63234532-2f738d00-c268-11e9-9156-fd4093b200c9.png)
![image](https://user-images.githubusercontent.com/24446694/63234543-3d291280-c268-11e9-815f-2c23321e4b02.png)
![image](https://user-images.githubusercontent.com/24446694/63234571-5cc03b00-c268-11e9-9e34-50334f385c75.png)

**Comment by YuFy1314** [comment]
这是npm热加载出来的错误
![image](https://user-images.githubusercontent.com/24446694/63234636-bf193b80-c268-11e9-8e76-88d8c46f9f36.png)

**Comment by YuFy1314** [comment]
不小心给关闭了把问题...

**Comment by OwnGhy** [comment]
试一下呢
```
const install = (Vue) => Vue.component(Toast.name, Toast);
export default install;
```

**Comment by YuFy1314** [comment]
还是不行   一样的效果

**Comment by OwnGhy** [comment]
发现你是在test-toast.vue里面去export，改成test-toast.js试试

**Comment by YuFy1314** [comment]
不是   我当然是在index.js里面export的   在vue里面import的

**Comment by OwnGhy** [comment]
嗷嗷，喵的看走眼了。

unique-ui.js是什么，你不是在index.js里面导出的么

**Comment by YuFy1314** [comment]
unique-ui.js是我打包过的文件

**Comment by OwnGhy** [comment]
export之前得调用一下install，好让组件挂在到vue上。

```
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}
```

**Comment by YuFy1314** [comment]
还是不行哎  直接引入就好使, 打包了就不行了
![image](https://user-images.githubusercontent.com/24446694/63244030-d834e300-c28e-11e9-9457-e50f014e53a9.png)

**Comment by YuFy1314** [comment]
我现在用的是你那个博客里面的代码了,  但是仍然不好使
![image](https://user-images.githubusercontent.com/24446694/63245115-d7518080-c291-11e9-9204-41d12c1ca1c8.png)

直接引入index.js源代码好使,   就是打包之后的不好使

**Comment by YuFy1314** [comment]
这是打包代码的配置文件: 

![image](https://user-images.githubusercontent.com/24446694/63245220-28617480-c292-11e9-98d4-08a363d77ad4.png)

**Comment by OwnGhy** [comment]
检查一下vue的版本，还有可以看一下你webpack的module的配置吗？
或者你项目push到git了的话，我本地试试呢～

**Comment by YuFy1314** [comment]
https://github.com/u-max/vue-unique-ui.git

clone完了之后需要改src/test/test-toast.vue 里面的引入文件, 改成test下的那个文件, 就是打包之后的文件, 就会有问题

**Comment by OwnGhy** [comment]
![image](https://user-images.githubusercontent.com/17840246/63319493-e0535800-c34c-11e9-8d74-95a5e65e6cb3.png)

![image](https://user-images.githubusercontent.com/17840246/63319529-011bad80-c34d-11e9-94e4-2dbb54b5c61c.png)

我把你打包位置修改为dist之后就可以了，我是了貌似只要不是test文件夹都可以，你先试一下叻

emm....这样奇葩的吗，我猜应该是test可能被当成单元测试的目录之类的吧，目前没有查到相关的解释....

**Comment by YuFy1314** [comment]
哈哈  这都可以, 多谢解决了我这个疑难问题, 对于这个真的是奇怪, 看来以后在起名字的时候尽量不用这些字眼

**Comment by OwnGhy** [comment]
嗯嗯没得事哈～
